name: ClearLag
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.clearlag.Main

commands:
  clearlag:
    description: Run ClearLag
    usage: "/clearlag"
    permission: clearlag.run
permissions:
  clearlag.run:
    description: "Allows user to run ClearLag"
    default: op
